server:
  port: 8012
websocket:
    bufferSize: 1024000
spring:
  jackson:
    joda-date-time-format: yyyy-MM-dd
    date-format: yyyy-MM-dd
  application:
    name: easywebsocket-server
  freemarker:
    request-context-attribute: req  #req访问request
    templateEncoding: UTF-8
    locale: zh_CN
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    date_format: yyyy-MM-dd
    time_format: HH:mm:ss
    datetime_format: yyyy-MM-dd HH:mm:ss
    settings:
      number_format: '0.##'   #数字格式化，无小数点

swagger2:
  enable: true
# 控制日志输出级别
logback:
  level: INFO
ios:
  payType: 0
